name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install web dependencies
        run: |
          cd web
          npm install

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run tests
        run: |
          cd server
          npm test
